// <auto-generated />
namespace DatabaseServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2300 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2300));
        
        string IMigrationMetadata.Id
        {
            get { return "201604111501180_2300"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
